channels:
- conda-forge
dependencies:
- python=3.12.2
- pip<=25.0
- pip:
  - mlflow==2.19.0
  - accelerate==1.3.0
  - defusedxml==0.7.1
  - dill==0.3.8
  - jinja2==3.1.4
  - numpy==1.26.4
  - pandas==2.2.3
  - scikit-learn==1.5.2
  - scipy==1.13.1
  - torch==2.5.1
  - torchvision==0.20.1
  - transformers==4.48.1
name: mlflow-env
